//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9179
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzicBokx {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class SavedSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SavedSettings defaultInstance = ((SavedSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SavedSettings())));
        
        public static SavedSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isLoop {
            get {
                return ((bool)(this["isLoop"]));
            }
            set {
                this["isLoop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./Media/gradient1.mp4")]
        public string bgUri {
            get {
                return ((string)(this["bgUri"]));
            }
            set {
                this["bgUri"] = value;
            }
        }
    }
}
